import { useEffect,useState,type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { cancelShift,createShift,listShifts,updateShift,type Shift,type ShiftInput } from '../api/shifts';
import { useAuth } from '../features/auth/auth-context';
const today=new Date().toISOString().slice(0,10);const empty:ShiftInput={date:today,startTime:'09:00',endTime:'17:00',role:'',notes:'',status:'DRAFT'};
export function ShiftsPage(){const{token}=useAuth();const[range,setRange]=useState({startDate:today,endDate:today});const[shifts,setShifts]=useState<Shift[]>([]);const[form,setForm]=useState<ShiftInput>(empty);const[editing,setEditing]=useState<string|null>(null);const[message,setMessage]=useState('');const[error,setError]=useState('');
  useEffect(()=>{if(!token)return;let active=true;setError('');void listShifts(token,range.startDate,range.endDate).then(result=>{if(active)setShifts(result);}).catch((caught:Error)=>{if(active)setError(caught.message);});return()=>{active=false;};},[token,range.startDate,range.endDate]);
  async function submit(event:FormEvent){event.preventDefault();if(!token)return;try{setError('');const saved=editing?await updateShift(token,editing,form):await createShift(token,form);setShifts(current=>editing?current.map(item=>item.id===editing?saved:item):[...current,saved]);setMessage(editing?'Shift updated successfully.':'Shift created successfully.');setEditing(null);setForm(empty);}catch(caught){setError(caught instanceof Error?caught.message:'Unable to save shift.');}}
  function edit(shift:Shift){setEditing(shift.id);setForm({employeeId:shift.employeeId,date:shift.date.slice(0,10),startTime:shift.startTime,endTime:shift.endTime,role:shift.role,notes:shift.notes,status:shift.status==='SCHEDULED'?'SCHEDULED':'DRAFT'});setMessage('');}
  async function cancel(id:string){if(!token)return;try{const saved=await cancelShift(token,id);setShifts(current=>current.map(item=>item.id===id?saved:item));setMessage('Shift cancelled successfully.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to cancel shift.');}}
  return <main className="dashboard-shell"><nav><strong>ShiftFlow</strong><Link to="/dashboard">Back to dashboard</Link></nav><section className="dashboard-card shifts-card"><p className="eyebrow">Manager workspace</p><h1>Shifts</h1><div className="shift-range"><label>From<input type="date" value={range.startDate} onChange={event=>setRange({...range,startDate:event.target.value})}/></label><label>To<input type="date" value={range.endDate} onChange={event=>setRange({...range,endDate:event.target.value})}/></label></div>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}<form className="shift-form" onSubmit={event=>void submit(event)}><label>Date<input required type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></label><label>Start time<input required type="time" value={form.startTime} onChange={event=>setForm({...form,startTime:event.target.value})}/></label><label>End time<input required type="time" value={form.endTime} onChange={event=>setForm({...form,endTime:event.target.value})}/></label><label>Required role<input required value={form.role} onChange={event=>setForm({...form,role:event.target.value})}/></label><label>Notes<input value={form.notes??''} onChange={event=>setForm({...form,notes:event.target.value})}/></label><label>Status<select value={form.status} onChange={event=>setForm({...form,status:event.target.value as 'DRAFT'|'SCHEDULED'})}><option>DRAFT</option><option>SCHEDULED</option></select></label><button type="submit">{editing?'Save shift':'Create shift'}</button></form><div className="shift-list">{shifts.map(shift=><article key={shift.id}><div><strong>{shift.role}</strong><p>{shift.date.slice(0,10)} · {shift.startTime}–{shift.endTime}</p><span className={`badge badge--${shift.status.toLowerCase()}`}>{shift.status}</span></div><div className="detail-actions"><button className="secondary" onClick={()=>edit(shift)}>Edit shift</button>{shift.status!=='CANCELLED'&&<button className="secondary danger" onClick={()=>void cancel(shift.id)}>Cancel shift</button>}</div></article>)}</div></section></main>;
}
